# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opensesame.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/openvpn-admin-256x256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableConnections = ConnectionTable(self.centralwidget)
        self.tableConnections.setGeometry(QtCore.QRect(0, 0, 591, 231))
        self.tableConnections.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableConnections.setTabKeyNavigation(False)
        self.tableConnections.setProperty("showDropIndicator", False)
        self.tableConnections.setDragDropOverwriteMode(False)
        self.tableConnections.setAlternatingRowColors(True)
        self.tableConnections.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableConnections.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableConnections.setObjectName("tableConnections")
        self.tableConnections.setColumnCount(4)
        self.tableConnections.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableConnections.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableConnections.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableConnections.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableConnections.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProfile = QtWidgets.QMenu(self.menubar)
        self.menuProfile.setObjectName("menuProfile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/gtk-quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionNew.setObjectName("actionNew")
        self.actionProperties = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProperties.setIcon(icon3)
        self.actionProperties.setObjectName("actionProperties")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon4)
        self.actionDelete.setObjectName("actionDelete")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon5)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnect.setIcon(icon6)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionLogging = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resources/log.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionLogging.setIcon(icon7)
        self.actionLogging.setObjectName("actionLogging")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resources/gtk-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout.setIcon(icon8)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/resources/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSettings.setIcon(icon9)
        self.actionSettings.setObjectName("actionSettings")
        self.actionForget_Password = QtWidgets.QAction(MainWindow)
        self.actionForget_Password.setObjectName("actionForget_Password")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionExit)
        self.menuProfile.addAction(self.actionNew)
        self.menuProfile.addAction(self.actionProperties)
        self.menuProfile.addAction(self.actionDelete)
        self.menuProfile.addSeparator()
        self.menuProfile.addAction(self.actionImport)
        self.menuProfile.addAction(self.actionExport)
        self.menuProfile.addSeparator()
        self.menuProfile.addAction(self.actionConnect)
        self.menuProfile.addAction(self.actionDisconnect)
        self.menuProfile.addAction(self.actionLogging)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuTools.addAction(self.actionSettings)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionForget_Password)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProfile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionProperties)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addAction(self.actionDisconnect)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLogging)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenSesame"))
        item = self.tableConnections.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableConnections.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableConnections.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gateway"))
        item = self.tableConnections.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProfile.setTitle(_translate("MainWindow", "Profile"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionDisconnect.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionLogging.setText(_translate("MainWindow", "Logging"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionForget_Password.setText(_translate("MainWindow", "Forget Passwords"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExport.setText(_translate("MainWindow", "Export"))

from .connectiontable import ConnectionTable
from . import ovpn_rc
