# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'properties.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Properties(object):
    def setupUi(self, Properties):
        Properties.setObjectName("Properties")
        Properties.setEnabled(True)
        Properties.resize(449, 373)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/gtk-properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Properties.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(Properties)
        self.buttonBox.setGeometry(QtCore.QRect(50, 330, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Properties)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 443, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(64, 64))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/resources/openvpn-client.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lineEditNickname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNickname.sizePolicy().hasHeightForWidth())
        self.lineEditNickname.setSizePolicy(sizePolicy)
        self.lineEditNickname.setMinimumSize(QtCore.QSize(258, 0))
        self.lineEditNickname.setObjectName("lineEditNickname")
        self.horizontalLayout_3.addWidget(self.lineEditNickname)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.lineEditDescription = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditDescription.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.horizontalLayout_4.addWidget(self.lineEditDescription)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabVPN = QtWidgets.QWidget()
        self.tabVPN.setObjectName("tabVPN")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabVPN)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 411, 156))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 7, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.lineEditGateway = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditGateway.sizePolicy().hasHeightForWidth())
        self.lineEditGateway.setSizePolicy(sizePolicy)
        self.lineEditGateway.setMinimumSize(QtCore.QSize(230, 0))
        self.lineEditGateway.setObjectName("lineEditGateway")
        self.gridLayout.addWidget(self.lineEditGateway, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditUserCert = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditUserCert.setEnabled(True)
        self.lineEditUserCert.setReadOnly(True)
        self.lineEditUserCert.setObjectName("lineEditUserCert")
        self.horizontalLayout_2.addWidget(self.lineEditUserCert)
        self.toolButtonUserCert = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButtonUserCert.setObjectName("toolButtonUserCert")
        self.horizontalLayout_2.addWidget(self.toolButtonUserCert)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditCACert = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditCACert.setEnabled(True)
        self.lineEditCACert.setReadOnly(True)
        self.lineEditCACert.setObjectName("lineEditCACert")
        self.horizontalLayout_5.addWidget(self.lineEditCACert)
        self.toolButtonCACert = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButtonCACert.setObjectName("toolButtonCACert")
        self.horizontalLayout_5.addWidget(self.toolButtonCACert)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 3, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditPrivKey = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditPrivKey.setEnabled(True)
        self.lineEditPrivKey.setReadOnly(True)
        self.lineEditPrivKey.setObjectName("lineEditPrivKey")
        self.horizontalLayout_6.addWidget(self.lineEditPrivKey)
        self.toolButtonPrivKey = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButtonPrivKey.setObjectName("toolButtonPrivKey")
        self.horizontalLayout_6.addWidget(self.toolButtonPrivKey)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tabVPN, "")
        self.tabTLSAuth = QtWidgets.QWidget()
        self.tabTLSAuth.setObjectName("tabTLSAuth")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabTLSAuth)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 371, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(15, 5, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBoxUseTLSAuth = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxUseTLSAuth.setObjectName("checkBoxUseTLSAuth")
        self.verticalLayout_3.addWidget(self.checkBoxUseTLSAuth)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditTLSAuth = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditTLSAuth.setEnabled(False)
        self.lineEditTLSAuth.setReadOnly(True)
        self.lineEditTLSAuth.setObjectName("lineEditTLSAuth")
        self.horizontalLayout_7.addWidget(self.lineEditTLSAuth)
        self.toolButtonTLSAuth = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.toolButtonTLSAuth.setEnabled(False)
        self.toolButtonTLSAuth.setObjectName("toolButtonTLSAuth")
        self.horizontalLayout_7.addWidget(self.toolButtonTLSAuth)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.comboBoxKeyDirection = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBoxKeyDirection.setEnabled(False)
        self.comboBoxKeyDirection.setObjectName("comboBoxKeyDirection")
        self.comboBoxKeyDirection.addItem("")
        self.comboBoxKeyDirection.addItem("")
        self.comboBoxKeyDirection.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxKeyDirection, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tabTLSAuth, "")
        self.tabAdvanced = QtWidgets.QWidget()
        self.tabAdvanced.setObjectName("tabAdvanced")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tabAdvanced)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 371, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(15, 5, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBoxPort = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxPort.setObjectName("checkBoxPort")
        self.horizontalLayout_8.addWidget(self.checkBoxPort)
        self.lineEditPort = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditPort.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPort.sizePolicy().hasHeightForWidth())
        self.lineEditPort.setSizePolicy(sizePolicy)
        self.lineEditPort.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEditPort.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditPort.setBaseSize(QtCore.QSize(0, 0))
        self.lineEditPort.setObjectName("lineEditPort")
        self.horizontalLayout_8.addWidget(self.lineEditPort)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.checkBoxUseLZO = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxUseLZO.setObjectName("checkBoxUseLZO")
        self.verticalLayout_4.addWidget(self.checkBoxUseLZO)
        self.checkBoxUseTCP = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxUseTCP.setObjectName("checkBoxUseTCP")
        self.verticalLayout_4.addWidget(self.checkBoxUseTCP)
        self.checkBoxUseTap = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxUseTap.setObjectName("checkBoxUseTap")
        self.verticalLayout_4.addWidget(self.checkBoxUseTap)
        self.checkBoxQueryAuth = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxQueryAuth.setObjectName("checkBoxQueryAuth")
        self.verticalLayout_4.addWidget(self.checkBoxQueryAuth)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.tabWidget.addTab(self.tabAdvanced, "")
        self.tabCustom = QtWidgets.QWidget()
        self.tabCustom.setObjectName("tabCustom")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tabCustom)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 381, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.tableCustomFields = CustomFieldTable(self.verticalLayoutWidget_4)
        self.tableCustomFields.setAlternatingRowColors(True)
        self.tableCustomFields.setColumnCount(2)
        self.tableCustomFields.setObjectName("tableCustomFields")
        self.tableCustomFields.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomFields.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomFields.setHorizontalHeaderItem(1, item)
        self.tableCustomFields.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.tableCustomFields)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.toolButtonAddCF = QtWidgets.QToolButton(self.verticalLayoutWidget_4)
        self.toolButtonAddCF.setMinimumSize(QtCore.QSize(25, 25))
        self.toolButtonAddCF.setMaximumSize(QtCore.QSize(25, 25))
        self.toolButtonAddCF.setObjectName("toolButtonAddCF")
        self.horizontalLayout_9.addWidget(self.toolButtonAddCF)
        self.toolButtonRemoveCF = QtWidgets.QToolButton(self.verticalLayoutWidget_4)
        self.toolButtonRemoveCF.setMinimumSize(QtCore.QSize(25, 25))
        self.toolButtonRemoveCF.setMaximumSize(QtCore.QSize(25, 25))
        self.toolButtonRemoveCF.setBaseSize(QtCore.QSize(0, 0))
        self.toolButtonRemoveCF.setObjectName("toolButtonRemoveCF")
        self.horizontalLayout_9.addWidget(self.toolButtonRemoveCF)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tabCustom, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Properties)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(Properties.reject)
        QtCore.QMetaObject.connectSlotsByName(Properties)
        Properties.setTabOrder(self.lineEditNickname, self.lineEditDescription)
        Properties.setTabOrder(self.lineEditDescription, self.tabWidget)
        Properties.setTabOrder(self.tabWidget, self.lineEditGateway)
        Properties.setTabOrder(self.lineEditGateway, self.toolButtonUserCert)
        Properties.setTabOrder(self.toolButtonUserCert, self.toolButtonCACert)
        Properties.setTabOrder(self.toolButtonCACert, self.toolButtonPrivKey)
        Properties.setTabOrder(self.toolButtonPrivKey, self.checkBoxUseTLSAuth)
        Properties.setTabOrder(self.checkBoxUseTLSAuth, self.toolButtonTLSAuth)
        Properties.setTabOrder(self.toolButtonTLSAuth, self.comboBoxKeyDirection)
        Properties.setTabOrder(self.comboBoxKeyDirection, self.checkBoxPort)
        Properties.setTabOrder(self.checkBoxPort, self.lineEditPort)
        Properties.setTabOrder(self.lineEditPort, self.checkBoxUseLZO)
        Properties.setTabOrder(self.checkBoxUseLZO, self.checkBoxUseTCP)
        Properties.setTabOrder(self.checkBoxUseTCP, self.checkBoxUseTap)
        Properties.setTabOrder(self.checkBoxUseTap, self.buttonBox)
        Properties.setTabOrder(self.buttonBox, self.lineEditPrivKey)
        Properties.setTabOrder(self.lineEditPrivKey, self.lineEditTLSAuth)
        Properties.setTabOrder(self.lineEditTLSAuth, self.lineEditCACert)
        Properties.setTabOrder(self.lineEditCACert, self.lineEditUserCert)

    def retranslateUi(self, Properties):
        _translate = QtCore.QCoreApplication.translate
        Properties.setWindowTitle(_translate("Properties", "Properties"))
        self.label_2.setText(_translate("Properties", "Nickname"))
        self.label_3.setText(_translate("Properties", "Description"))
        self.label_4.setText(_translate("Properties", "Gateway"))
        self.label_5.setText(_translate("Properties", "User Certificate"))
        self.label_6.setText(_translate("Properties", "CA Certificate"))
        self.label_7.setText(_translate("Properties", "Private Key"))
        self.toolButtonUserCert.setText(_translate("Properties", "..."))
        self.toolButtonCACert.setText(_translate("Properties", "..."))
        self.toolButtonPrivKey.setText(_translate("Properties", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVPN), _translate("Properties", "VPN"))
        self.checkBoxUseTLSAuth.setText(_translate("Properties", "Use additional TLS Authentication"))
        self.label_9.setText(_translate("Properties", "Key File"))
        self.toolButtonTLSAuth.setText(_translate("Properties", "..."))
        self.label_10.setText(_translate("Properties", "Key Direction"))
        self.comboBoxKeyDirection.setItemText(0, _translate("Properties", "None"))
        self.comboBoxKeyDirection.setItemText(1, _translate("Properties", "0"))
        self.comboBoxKeyDirection.setItemText(2, _translate("Properties", "1"))
        self.label_11.setText(_translate("Properties", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">If key direction is used, it must be the opposite of that used on the VPN peer. For example, if the per uses \'1\', this connection must use \'0\'. If you are unsure what value to use, contact your system administrator.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTLSAuth), _translate("Properties", "TLS Auth"))
        self.checkBoxPort.setText(_translate("Properties", "Use custom gateway port"))
        self.checkBoxUseLZO.setText(_translate("Properties", "Use LZO data compression"))
        self.checkBoxUseTCP.setText(_translate("Properties", "Use a TCP connection"))
        self.checkBoxUseTap.setText(_translate("Properties", "Use a TAP device"))
        self.checkBoxQueryAuth.setText(_translate("Properties", "Query Username & Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvanced), _translate("Properties", "Advanced"))
        self.label_8.setText(_translate("Properties", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; font-style:italic;\">Warning: </span><span style=\" font-size:7pt;\">If you goof up your config by using custom fields, don\'t complain</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">to me. See README.TXT. You have been warned.</span></p></body></html>"))
        item = self.tableCustomFields.horizontalHeaderItem(0)
        item.setText(_translate("Properties", "Field"))
        item = self.tableCustomFields.horizontalHeaderItem(1)
        item.setText(_translate("Properties", "Value"))
        self.toolButtonAddCF.setText(_translate("Properties", "+"))
        self.toolButtonRemoveCF.setText(_translate("Properties", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCustom), _translate("Properties", "Custom"))

from .customfieldtable import CustomFieldTable
from . import ovpn_rc
