# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rob\projects\ovpnclient\trunk\ui\properties.ui'
#
# Created: Mon Jul 20 18:21:29 2009
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Properties(object):
    def setupUi(self, Properties):
        Properties.setObjectName("Properties")
        Properties.setEnabled(True)
        Properties.resize(449, 373)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/gtk-properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Properties.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(Properties)
        self.buttonBox.setGeometry(QtCore.QRect(50, 330, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtGui.QWidget(Properties)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 443, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(64, 64))
        self.label.setPixmap(QtGui.QPixmap(":/resources/openvpn-client.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lineEditNickname = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNickname.sizePolicy().hasHeightForWidth())
        self.lineEditNickname.setSizePolicy(sizePolicy)
        self.lineEditNickname.setMinimumSize(QtCore.QSize(258, 0))
        self.lineEditNickname.setObjectName("lineEditNickname")
        self.horizontalLayout_3.addWidget(self.lineEditNickname)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.lineEditDescription = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEditDescription.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.horizontalLayout_4.addWidget(self.lineEditDescription)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabVPN = QtGui.QWidget()
        self.tabVPN.setObjectName("tabVPN")
        self.gridLayoutWidget = QtGui.QWidget(self.tabVPN)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 411, 156))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(-1, 7, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        self.lineEditGateway = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditGateway.sizePolicy().hasHeightForWidth())
        self.lineEditGateway.setSizePolicy(sizePolicy)
        self.lineEditGateway.setMinimumSize(QtCore.QSize(230, 0))
        self.lineEditGateway.setObjectName("lineEditGateway")
        self.gridLayout.addWidget(self.lineEditGateway, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditUserCert = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditUserCert.setEnabled(True)
        self.lineEditUserCert.setReadOnly(True)
        self.lineEditUserCert.setObjectName("lineEditUserCert")
        self.horizontalLayout_2.addWidget(self.lineEditUserCert)
        self.toolButtonUserCert = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonUserCert.setObjectName("toolButtonUserCert")
        self.horizontalLayout_2.addWidget(self.toolButtonUserCert)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 3, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditCACert = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditCACert.setEnabled(True)
        self.lineEditCACert.setReadOnly(True)
        self.lineEditCACert.setObjectName("lineEditCACert")
        self.horizontalLayout_5.addWidget(self.lineEditCACert)
        self.toolButtonCACert = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonCACert.setObjectName("toolButtonCACert")
        self.horizontalLayout_5.addWidget(self.toolButtonCACert)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 3, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditPrivKey = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditPrivKey.setEnabled(True)
        self.lineEditPrivKey.setReadOnly(True)
        self.lineEditPrivKey.setObjectName("lineEditPrivKey")
        self.horizontalLayout_6.addWidget(self.lineEditPrivKey)
        self.toolButtonPrivKey = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonPrivKey.setObjectName("toolButtonPrivKey")
        self.horizontalLayout_6.addWidget(self.toolButtonPrivKey)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tabVPN, "")
        self.tabTLSAuth = QtGui.QWidget()
        self.tabTLSAuth.setObjectName("tabTLSAuth")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tabTLSAuth)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 371, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(15, 5, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBoxUseTLSAuth = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxUseTLSAuth.setObjectName("checkBoxUseTLSAuth")
        self.verticalLayout_3.addWidget(self.checkBoxUseTLSAuth)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditTLSAuth = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditTLSAuth.setEnabled(False)
        self.lineEditTLSAuth.setReadOnly(True)
        self.lineEditTLSAuth.setObjectName("lineEditTLSAuth")
        self.horizontalLayout_7.addWidget(self.lineEditTLSAuth)
        self.toolButtonTLSAuth = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.toolButtonTLSAuth.setEnabled(False)
        self.toolButtonTLSAuth.setObjectName("toolButtonTLSAuth")
        self.horizontalLayout_7.addWidget(self.toolButtonTLSAuth)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.comboBoxKeyDirection = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.comboBoxKeyDirection.setEnabled(False)
        self.comboBoxKeyDirection.setObjectName("comboBoxKeyDirection")
        self.comboBoxKeyDirection.addItem(QtCore.QString())
        self.comboBoxKeyDirection.addItem(QtCore.QString())
        self.comboBoxKeyDirection.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.comboBoxKeyDirection, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tabTLSAuth, "")
        self.tabAdvanced = QtGui.QWidget()
        self.tabAdvanced.setObjectName("tabAdvanced")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tabAdvanced)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 371, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(15, 5, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBoxPort = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxPort.setObjectName("checkBoxPort")
        self.horizontalLayout_8.addWidget(self.checkBoxPort)
        self.lineEditPort = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditPort.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPort.sizePolicy().hasHeightForWidth())
        self.lineEditPort.setSizePolicy(sizePolicy)
        self.lineEditPort.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEditPort.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditPort.setBaseSize(QtCore.QSize(0, 0))
        self.lineEditPort.setObjectName("lineEditPort")
        self.horizontalLayout_8.addWidget(self.lineEditPort)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.checkBoxUseLZO = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxUseLZO.setObjectName("checkBoxUseLZO")
        self.verticalLayout_4.addWidget(self.checkBoxUseLZO)
        self.checkBoxUseTCP = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxUseTCP.setObjectName("checkBoxUseTCP")
        self.verticalLayout_4.addWidget(self.checkBoxUseTCP)
        self.checkBoxUseTap = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBoxUseTap.setObjectName("checkBoxUseTap")
        self.verticalLayout_4.addWidget(self.checkBoxUseTap)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.tabWidget.addTab(self.tabAdvanced, "")
        self.tabCustom = QtGui.QWidget()
        self.tabCustom.setObjectName("tabCustom")
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tabCustom)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 381, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.tableCustomFields = CustomFieldTable(self.verticalLayoutWidget_4)
        self.tableCustomFields.setAlternatingRowColors(True)
        self.tableCustomFields.setColumnCount(2)
        self.tableCustomFields.setObjectName("tableCustomFields")
        self.tableCustomFields.setColumnCount(2)
        self.tableCustomFields.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableCustomFields.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableCustomFields.setHorizontalHeaderItem(1, item)
        self.tableCustomFields.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.tableCustomFields)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.toolButtonAddCF = QtGui.QToolButton(self.verticalLayoutWidget_4)
        self.toolButtonAddCF.setMinimumSize(QtCore.QSize(25, 25))
        self.toolButtonAddCF.setMaximumSize(QtCore.QSize(25, 25))
        self.toolButtonAddCF.setObjectName("toolButtonAddCF")
        self.horizontalLayout_9.addWidget(self.toolButtonAddCF)
        self.toolButtonRemoveCF = QtGui.QToolButton(self.verticalLayoutWidget_4)
        self.toolButtonRemoveCF.setMinimumSize(QtCore.QSize(25, 25))
        self.toolButtonRemoveCF.setMaximumSize(QtCore.QSize(25, 25))
        self.toolButtonRemoveCF.setBaseSize(QtCore.QSize(0, 0))
        self.toolButtonRemoveCF.setObjectName("toolButtonRemoveCF")
        self.horizontalLayout_9.addWidget(self.toolButtonRemoveCF)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tabCustom, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Properties)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Properties.reject)
        QtCore.QMetaObject.connectSlotsByName(Properties)
        Properties.setTabOrder(self.lineEditNickname, self.lineEditDescription)
        Properties.setTabOrder(self.lineEditDescription, self.tabWidget)
        Properties.setTabOrder(self.tabWidget, self.lineEditGateway)
        Properties.setTabOrder(self.lineEditGateway, self.toolButtonUserCert)
        Properties.setTabOrder(self.toolButtonUserCert, self.toolButtonCACert)
        Properties.setTabOrder(self.toolButtonCACert, self.toolButtonPrivKey)
        Properties.setTabOrder(self.toolButtonPrivKey, self.checkBoxUseTLSAuth)
        Properties.setTabOrder(self.checkBoxUseTLSAuth, self.toolButtonTLSAuth)
        Properties.setTabOrder(self.toolButtonTLSAuth, self.comboBoxKeyDirection)
        Properties.setTabOrder(self.comboBoxKeyDirection, self.checkBoxPort)
        Properties.setTabOrder(self.checkBoxPort, self.lineEditPort)
        Properties.setTabOrder(self.lineEditPort, self.checkBoxUseLZO)
        Properties.setTabOrder(self.checkBoxUseLZO, self.checkBoxUseTCP)
        Properties.setTabOrder(self.checkBoxUseTCP, self.checkBoxUseTap)
        Properties.setTabOrder(self.checkBoxUseTap, self.buttonBox)
        Properties.setTabOrder(self.buttonBox, self.lineEditPrivKey)
        Properties.setTabOrder(self.lineEditPrivKey, self.lineEditTLSAuth)
        Properties.setTabOrder(self.lineEditTLSAuth, self.lineEditCACert)
        Properties.setTabOrder(self.lineEditCACert, self.lineEditUserCert)

    def retranslateUi(self, Properties):
        Properties.setWindowTitle(QtGui.QApplication.translate("Properties", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Properties", "Nickname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Properties", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Properties", "Gateway", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Properties", "User Certificate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Properties", "CA Certificate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Properties", "Private Key", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonUserCert.setText(QtGui.QApplication.translate("Properties", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonCACert.setText(QtGui.QApplication.translate("Properties", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonPrivKey.setText(QtGui.QApplication.translate("Properties", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVPN), QtGui.QApplication.translate("Properties", "VPN", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseTLSAuth.setText(QtGui.QApplication.translate("Properties", "Use additional TLS Authentication", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Properties", "Key File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonTLSAuth.setText(QtGui.QApplication.translate("Properties", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Properties", "Key Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxKeyDirection.setItemText(0, QtGui.QApplication.translate("Properties", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxKeyDirection.setItemText(1, QtGui.QApplication.translate("Properties", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxKeyDirection.setItemText(2, QtGui.QApplication.translate("Properties", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Properties", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">If key direction is used, it must be the opposite of that used on the VPN peer. For example, if the per uses \'1\', this connection must use \'0\'. If you are unsure what value to use, contact your system administrator.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTLSAuth), QtGui.QApplication.translate("Properties", "TLS Auth", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPort.setText(QtGui.QApplication.translate("Properties", "Use custom gateway port", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseLZO.setText(QtGui.QApplication.translate("Properties", "Use LZO data compression", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseTCP.setText(QtGui.QApplication.translate("Properties", "Use a TCP connection", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUseTap.setText(QtGui.QApplication.translate("Properties", "Use a TAP device", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvanced), QtGui.QApplication.translate("Properties", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Properties", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; font-style:italic;\">Warning: </span><span style=\" font-size:7pt;\">If you goof up your config by using custom fields, don\'t complain</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">to me. See README.TXT. You have been warned.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tableCustomFields.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Properties", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.tableCustomFields.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Properties", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonAddCF.setText(QtGui.QApplication.translate("Properties", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonRemoveCF.setText(QtGui.QApplication.translate("Properties", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCustom), QtGui.QApplication.translate("Properties", "Custom", None, QtGui.QApplication.UnicodeUTF8))

from customfieldtable import CustomFieldTable
import ovpn_rc
import ovpn_rc
import ovpn_rc
import ovpn_rc
import ovpn_rc
import ovpn_rc
import ovpn_rc
import ovpn_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Properties = QtGui.QDialog()
    ui = Ui_Properties()
    ui.setupUi(Properties)
    Properties.show()
    sys.exit(app.exec_())

